name: Multiple shells commands
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [closed, assigned, opened, reopened]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
